import type { Metadata } from "next";
import "./globals.css";
import { Raleway } from "next/font/google";
import Navbar from "@/components/common/Navbar";
import ConditionalFooter from "@/components/common/conditionalFooter";
import Providers from "./provider";
import { Toaster } from "sonner";
import "@/api/client";

const raleway = Raleway({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-raleway",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${raleway.variable}`}>
      <body
        className="flex flex-col min-h-screen"
        suppressHydrationWarning={true}
      >
        <Toaster position="top-right" richColors />

        <Providers>
          {/* <Navbar /> */}
          {children}
          <ConditionalFooter />
        </Providers>
      </body>
    </html>
  );
}
